name       : rarian
version    : 0.8.1
release    : 5
source     :
    - https://download.gnome.org/sources/rarian/0.8/rarian-0.8.1.tar.bz2 : aafe886d46e467eb3414e91fa9e42955bd4b618c3e19c42c773026b205a84577
homepage   : http://www.gnome.org
license    : GPL-3.0
component  :
    - desktop.gnome.doc
    - ^librarian: desktop.gnome.doc
    - ^librarian-devel: desktop.gnome.doc
summary    :
    - Tools for librarian, designed to replace scrollkeeper
    - ^librarian : Documentation metadata library based on the proposed Freedesktop.org spec. Rarian is designed to be a replacement for ScrollKeeper.
    - ^librarian-devel : Development files for librarian
description:
    - Tools for librarian, designed to replace scrollkeeper
    - ^librarian : Documentation metadata library based on the proposed Freedesktop.org spec. Rarian is designed to be a replacement for ScrollKeeper.
    - ^librarian-devel : Development files for librarian
patterns   :
    - ^librarian :
        - /usr/lib64/lib*.so.*
        - /usr/share/doc
        - /usr/share/help
        - /usr/share/librarian
        - /var/lib/rarian
    - ^librarian-devel :
        - /usr/include
        - /usr/lib64/pkgconfig
        - /usr/lib64/lib*.so
    - /usr/bin
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
